export const colorPrimario = "#FF515F"
export const colorSecundario= "#ff5050"
export const fuenteTitulos = "'Bebas Neue', cursive"
export const fuenteTexto = "'Source Sans Pro', sans-serif"
export const colorDeFondo = "#191919"
export const inputColor = "#53585D"